### ISSUE TITLE
[BUG/Feature Request]

### ISSUE THREAD

**Issue by heyitshestia** [Jesewe/cs2-triggerbot#11]
It has somehow become impossible to assign a mousekey like xbutton1 or 2 as the trigger key since the last update. Not even reassigning a mouse key in ghub or any other emulator works.

**Comment by Jesewe** [comment]
I know about this issue, I pointed out the information in the release about removing the ability to set `TriggerKey` on side keys, the plan is to bring them back in the next updates, but for now you can use the previous versions.

**Comment by heyitshestia** [comment]
You sure did. Sorry, didn't see that. Either way it works extremely well so keep it up! 😄

**Comment by Jesewe** [comment]
This issue has been successfully addressed in version **[v1.1.6](https://github.com/Jesewe/cs2-triggerbot/releases/tag/v1.1.6)**.  

Users can now assign `x1` or `x2` as trigger keys directly, with no need for external remapping tools.
