### ISSUE TITLE
[BUG] Unexpected error: Could not read memory at: 5208, length: 4 - GetLastError: 299

### ISSUE THREAD

**Issue by ParsKod** [Jesewe/cs2-triggerbot#17]
**Describe the bug**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Jesewe** [comment]
Offsets updated due to overnight update

**Comment by ParsKod** [comment]
yes, I saw that they were displaced, but I don't understand how to fix it

чт, 7 нояб. 2024 г. в 14:04, ItsJesewe ***@***.***>:

**Comment by Jesewe** [comment]
> yes, I saw that they were displaced, but I don't understand how to fix it чт, 7 нояб. 2024 г. в 14:04, ItsJesewe ***@***.***>:

you don't need to do anything, you can use the programme when the game is updated - the offsets are updated, the programme itself updates them in its code.

```python
class Utility:
    @staticmethod
    def fetch_offsets():
        try:
            # Fetch offsets and client data directly from the server
            response_offset = get("https://raw.githubusercontent.com/a2x/cs2-dumper/main/output/offsets.json")
            response_client = get("https://raw.githubusercontent.com/a2x/cs2-dumper/main/output/client_dll.json")

            if response_offset.status_code != 200 or response_client.status_code != 200:
                logging.error("Failed to fetch offsets from server.")
                return None, None

            offset = response_offset.json()
            client = response_client.json()

            return offset, client
        except Exception as e:
            logging.error(f"Failed to fetch offsets: {e}")
            return None, None
```

**Comment by ParsKod** [comment]
but my offsets are not updated when opening the program and the game

чт, 7 нояб. 2024 г. в 15:51, ItsJesewe ***@***.***>:

**Comment by Jesewe** [comment]
> but my offsets are not updated when opening the program and the game

Have you checked the program to see if it works? Provide a screenshot of the program, as well as the time and date when you ran it.
