### ISSUE TITLE
feature

### ISSUE THREAD

**Issue by sailozxsa** [Jesewe/cs2-triggerbot#18]
hi, i use ur triggerbot and this great) ive an idea for next update, if it is possible to make it so that there is a delay after each shot? and so that it can be configured via pyqt6?

**Comment by Jesewe** [comment]
> hi, i use ur triggerbot and this great) ive an idea for next update, if it is possible to make it so that there is a delay after each shot? and so that it can be configured via pyqt6?

Accepted for development

**Comment by Jesewe** [comment]
This issue has been successfully addressed in version [v1.1.7](https://github.com/Jesewe/cs2-triggerbot/releases/tag/v1.1.7).
