### ISSUE TITLE
FACEIT

### ISSUE THREAD

**Issue by Straiko** [Jesewe/cs2-triggerbot#2]
Is it possible to set up a trigger to work on the FACEIT?

**Comment by Jesewe** [comment]
We don't have the option to move the project for Faceit, as there are no options for testing the _“software”_ due to **anti-cheat**.

**Comment by eliano-dev** [comment]
how to add mouse button 5 to trigger key?

**Comment by Straiko** [comment]
I'll send you the code with the side button in 10 hours

**Comment by Straiko** [comment]
I'll send you the code with the side button in 10 hours

**Comment by Straiko** [comment]
> I'll send you the code with the side button in 10 hours

Maybe a little earlier

**Comment by Straiko** [comment]
> I'll send you the code with the side button in 10 hours

Maybe a little earlier

**Comment by eliano-dev** [comment]
if you can explain how you added the side buttons that would be perfect! Thank you.

**Comment by Jesewe** [comment]
> how to add mouse button 5 to trigger key?

Unfortunately I tried to assign the trigger bot to the mouse side keys but the program doesn't recognize them, in upcoming updates I will try to fix this.

**Comment by Jesewe** [comment]
And yes, I want to ask, how would you like the `TRIGGER_KEY` variable to change, with the config.ini file, or your guesses?

**Comment by eliano-dev** [comment]
whichever way u find easier to manipulate...

**Comment by Jesewe** [comment]
> whichever way u find easier to manipulate...

 **Soon enough.**
```@staticmethod
    def load_config():
        """Loads configuration settings from a config.ini file."""
        config = configparser.ConfigParser()
        if not os.path.exists(Utility.CONFIG_FILE):
            config['Settings'] = {
                'trigger_key': 'MOUSE5'  # Default trigger key
            }
            with open(Utility.CONFIG_FILE, 'w') as configfile:
                config.write(configfile)
        else:
            config.read(Utility.CONFIG_FILE)
        return config
 ```

**Comment by eliano-dev** [comment]
if i test the mouse button 5 with pyniput listener it returns that the name of the side mouse buttons are called Button.x1 and Button.x2. I hope this would save some time debugging errors?

**Comment by Jesewe** [comment]
> if i test the mouse button 5 with pynput listener it returns that the name of the side mouse buttons are called Button.x1 and Button.x2. I hope this would save some time debugging errors?

The script code has been written for a long time, the only thing left is to test it in the game, as well as modify `README.md`. 
But thank you so much.

![ScreenCode](https://github.com/user-attachments/assets/d822ad7c-e672-4361-9c89-6a3eb445be75)
![ScreenCode2](https://github.com/user-attachments/assets/80c2db37-2e7c-4fc6-96fa-8355cf279f1b)

**Comment by eliano-dev** [comment]
when would it be published?

**Comment by Jesewe** [comment]
> when would it be published?

Within _3 days_.

**Comment by Jesewe** [comment]
> when would it be published?

The project has been updated to version: **[v1.0.9](https://github.com/Jesewe/cs2-triggerbot/releases/tag/v1.0.9)**

**Full Changelog**: https://github.com/Jesewe/cs2-triggerbot/compare/v1.0.8...v1.0.9

**Comment by eliano-dev** [comment]
You're awesome man! God bless you

**Comment by eliano-dev** [comment]
one last question, if i want the second side button to be the trigger where can i change that?

**Comment by Jesewe** [comment]
> one last question, if i want the second side button to be the trigger where can i change that?(MOUSE BUTTON 4)

The `config.ini` file is located in the `%LOCALAPPDATA%\Requests\ItsJesewe\` directory.

TriggerKey = x2 **(MOUSE 5)**
TriggerKey = x1 **(MOUSE 4)**

**Comment by eliano-dev** [comment]
Hello, hope you're doing well.
Today i experienced this error:
Unexpected error: Could not read memory at: 5208, length: 4 - GetLastError: 299

**Comment by Jesewe** [comment]
> Hello, hope you're doing well. Today i experienced this error: Unexpected error: Could not read memory at: 5208, length: 4 - GetLastError: 299

Hello, everything's fine. The offsets were updated a **few hours** ago. _Open a new **"issue"** next time._
