### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by stevenpompy** [Jesewe/cs2-triggerbot#32]
### Steps to Reproduce*
Detailed steps to reproduce the issue:
1. Trying to use X1 or x2 key
2. 
3. 

### Actual Behavior
What actually happened? Include logs or screenshots if applicable.
Nothing happens

### Environment Details
- **OS:**   Windows 11 
- **Python Version:** Python 3.13.0 
- **Version of CS2 TriggerBot:** e.g., v1.1.5
- **Game Version:** e.g., Latest CS2 update

### Logs
Attach logs from `%LOCALAPPDATA%\Requests\ItsJesewe\crashes\tb_logs.log` if possible.

### Additional Context
Any other information that might be helpful for debugging.
[tb_logs.log](https://github.com/user-attachments/files/18223514/tb_logs.log)

**Comment by Jesewe** [comment]
Based on tb_logs.log: 
`Unexpected error: ("Key 'mouse4' is not mapped to any known key.", ValueError("Key name 'mouse4' is not mapped to any known key."))`

Your TriggerKey is assigned to mouse4. To assign to the side keys, use - `x1` (Mouse 4) or `x2` (Mouse 5).
