### ISSUE TITLE
Update requirements.txt to include python-dateutil

### ISSUE THREAD

**Issue by joaoguiIherme** [Jesewe/cs2-triggerbot#33]
### **Steps to Reproduce**

1. Clone the repository.
2. Run `pip install -r .\requirements.txt` to install the dependencies.
3. Run `python .\main.py` to start the application.

---

### **Actual Behavior**

The application fails to start and returns the following error:

```plaintext
ModuleNotFoundError: No module named 'dateutil'
```

---

### **Expected Behavior**

The application should run without errors after installing the dependencies.

---

### **Environment Details**

- **OS:** Windows 10/11
- **Python Version:** 3.9
- **TriggerBot Version:** v1.2.1
- **Game Version:** Latest CS2 update

---

### **Logs**

Full error:

```plaintext
Traceback (most recent call last):
  File "C:\Users\...\main.py", line 6, in <module>
    from classes.main_window import MainWindow
  File "C:\Users\...\classes\main_window.py", line 9, in <module>
    from classes.utility import Utility
  File "C:\Users\...\classes\utility.py", line 4, in <module>
    from dateutil.parser import parse as parse_date
ModuleNotFoundError: No module named 'dateutil'
```

---

### **Resolution**

The issue was fixed by running:

```bash
pip install python-dateutil
```

This indicates that the `python-dateutil` module is missing from the `requirements.txt` file.

---

### **Recommended Action**

Regenerate the `requirements.txt` file with all installed dependencies to include `python-dateutil`. The suggested command is:

```bash
pip freeze > requirements.txt
```

This ensures that all necessary dependencies for the project are listed.

---

### **Additional Context**

If needed, I can contribute with a PR to fix the `requirements.txt` file.

**Comment by Jesewe** [comment]
You can send a pull request
