### ISSUE TITLE
CS2 Perfectworld cannot use this program

### ISSUE THREAD

**Issue by CNLiNXinYA** [Jesewe/cs2-triggerbot#4]
When I added the startup option - perfectworld to the game and entered it into the Chinese server, this program was unable to take effect
Currently, it can only take effect on international servers

-perfectworld

**Comment by Jesewe** [comment]
Interesting, never heard of this **startup parameter** before...

**Comment by CNLiNXinYA** [comment]
> Interesting, never heard of this **startup parameter** before...
this is CS China Server,use -perfectworld you can join china server
