### ISSUE TITLE
models

### ISSUE THREAD

**Issue by Straiko** [Jesewe/cs2-triggerbot#8]
Is there a way to make the bot trigger work for all models, and not just for the opposite team?

**Comment by Jesewe** [comment]
Explore the new version [v1.1.1](https://github.com/Jesewe/cs2-triggerbot/releases/tag/v1.1.1). You can now configure the bot to attack teammates by setting the `AttackOnTeammates` value in the configuration file (`config.ini`). By default this value is `False` to avoid friendly fire.
